### ISSUE TITLE
I do not understand

### ISSUE THREAD

**Issue by Tofutush** [LLK/scratch-paint#1130]
How do you exactly, like, run the paint editor? Do you have to install Git and Node.js(what *are* they anyway?)? How do you download it? How do you run the "npm install" thing? These are either not explained clearly, or it's just me and my bad English.

**Comment by apple502j** [comment]
They are not explained because they are considered too basic to list, probably. You can search "how to install Git" or "what is Node.js" on Google or something.

**Comment by fsih** [comment]
Hi! If you want to just view the standalone paint editor, you can see it at https://llk.github.io/scratch-paint/

If you want to compile the code yourself to run it, e.g. if you want to make changes to the code and then test them out, then you need to install special programs in order to get a copy of all of the source code (Git), and then to compile all of the source code (node) into a webpage you can view on your browser.

All of the projects on GitHub will require you to learn how to use Git (https://git-scm.com/) in order to get copies of the source code hosted here. How you install Git depends on your operating system. What operating system are you using?

**Comment by Tofutush** [comment]
Windows, but thanks, I think I get it now.
I'm still going to fork it though.
