### ISSUE TITLE
Revert color fill, too many undo states

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#132]
I wanted to undo a color fill. However, it took about twenty clicks because each undo would show a color I scrubbed to while picking the color.
from Eric S

**Comment by jwzimmer-zz** [comment]
@mewtaylor reported this as well:
> the undo/redo stack seemed to add every small change in hue that I made – so it took a really long time to get back to my original color

FF 56, OSX 10.12

**Comment by griffpatch** [comment]
I find that when using the undo button I am having my current color changed to the previous color used rather than the one I was about to paint with? I believe it would be better for the active color to stay selected after pressing undo? The usual workflow for painting, is choose a color, paint... oops mistake, click undo and paint again... but when doing this the next stroke made is in the wrong color as it reverted to the previous one when I clicked undo? It might be down to the selection changing to a different shape when clicking undo, and thus the current color changes too... but perhaps if the current tool is not the selection tool then it should not do this?
