### ISSUE TITLE
Color state shows wrong thing

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#142]
Fill says it's mixed, but it's not, it's all purple
<img width="567" alt="screen shot 2017-10-27 at 14 35 16" src="https://user-images.githubusercontent.com/2855464/32122674-2d649eb0-bb2f-11e7-88db-ac4ed36ea22a.png">

Later the same shape showed the fill as transparent
<img width="603" alt="screen shot 2017-10-27 at 14 44 03" src="https://user-images.githubusercontent.com/2855464/32122695-3ff42b18-bb2f-11e7-8e4e-0cbc710d3daa.png">

**Comment by fsih** [comment]
With reshape tool selected, fill and stroke widgets report incorrect color (clear instead of red)
from ericr

**Comment by griffpatch** [comment]
This issue is occurs when the selection is a compound shape (i.e. a shape with a hole in it).
If you 'paint' a line, then you can reselect that line using the selector tool and get the same color appear in the palette. But if you paint a hollow circle and then select that, then the palette shows the mixed color icon. It's also problematic that the next paint operation you perform appears to always then switch the color to purple.
