### ISSUE TITLE
Can't select front shape with the reshape tool if the back shape is selected

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-paint#204]
### Expected Behavior

When using the reshape tool, clicking on a shape in front of the selected one should select the front shape.

### Actual Behavior
![Screenshot-2017-11-20 Scratch 3 0 GUI(3).png](https://codetreeusercontent.s3.amazonaws.com/uploads/9dfb3f06-7fd0-4e72-b1d4-c32e7a366c9e/Screenshot-2017-11-20+Scratch+3+0+GUI%283%29.png)

When the green rectangle is selected with the reshape tool as shown, clicking on the left side of the ellipse where it overlaps the rectangle does not select the ellipse. Clicking on the part that does not overlap will select the ellipse.

**Comment by fsih** [comment]
We have to think carefully about how this should work. This behavior was added intentionally because it was easy to accidentally change focus when working on the shape behind (for instance, what if you want to add a control point to the right edge of the rectangle right now? Should you have to move everything in front out of the way and then move it back after?)

**Comment by chrisgarrity** [comment]
Yes, but I ran into this because I was editing the shape in front, but clicked off the edge when trying to add a point. In my case the front shape was entirely surrounded  by the back one, and I was unable to reselect the front shape with the reshape tool. I was trying to edit a very small shape on top of a full background.
