### ISSUE TITLE
Fix the watermelon sprite (and check for others)

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#209]
The watermelon sprite isn't importing.

**Comment by paulkaplan** [comment]
It seems to be that paperjs cannot import SVGs that use the `<svg:` namespace. For example, the watermelon costume for some reason namespaces all of the elements with `svg:`. it seems that inkscape did this. You can also see it in projects like https://llk.github.io/scratch-gui/develop/#177260519 where many costumes do not import.

Seems like a paperjs bug, because the svg does declare an `svg` namespace correctly (xmlns:svg="http://www.w3.org/2000/svg"), and chrome/preview both support it. But as a simple workaround, a string replacement before importing fixes this (`svg.split('svg:').join('')`) does fix it.

**Comment by paulkaplan** [comment]
Not sure if you get notifications if I don't tag you, so for completeness, @fsih ^ :)

**Comment by paulkaplan** [comment]
Also, wrote a script to check all the other costumes in the library. Only watermelon a, b and c suffer from that svg: namespace pathology.
