### ISSUE TITLE
Select bounding box scales with zoom

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-paint#219]
**Currently on Develop**
Browser: Chrome 63.0.3239.84
OS: Mac OS X 10.11.6
![bounding box sizing with zoom](https://user-images.githubusercontent.com/3409578/33965406-b48ff17c-e029-11e7-92cd-97422aa5de11.gif)

1. Select an object
2. Zoom in or out
3. Bounding box UI scales relative to zoom level

**Expected Behavior**
The bounding box UI (in particular the drag handles) should have a fixed size. Zooming in, not so bad, but zooming out can result in tiny handles.

**Comment by Jacco** [comment]
This can be solved by calling setSelectedItems when zooming in paint-editor.jsx

    handleZoomIn () {
        zoomOnSelection(PaintEditor.ZOOM_INCREMENT);
        if (this.props.setSelectedItems) {
            this.props.setSelectedItems();
        }
    }
    handleZoomOut () {
        zoomOnSelection(-PaintEditor.ZOOM_INCREMENT);
        if (this.props.setSelectedItems) {
            this.props.setSelectedItems();
        }
    }
    handleZoomReset () {
        resetZoom();
        if (this.props.setSelectedItems) {
            this.props.setSelectedItems();
        }        
    }

Also the zoom functions need to be bound in the constructor too, otherwise "this" is undefined:

    constructor (props) {
        super(props);
        bindAll(this, [
            'handleUpdateSvg',
            'handleUndo',
            'handleRedo',
            'handleSendBackward',
            'handleSendForward',
            'handleSendToBack',
            'handleSendToFront',
            'handleGroup',
            'handleUngroup',
            'handleZoomIn',
            'handleZoomOut',
            'handleZoomReset',
            'canRedo',
            'canUndo',
            'onMouseDown',
            'setCanvas',
            'startEyeDroppingLoop',
            'stopEyeDroppingLoop'
        ]);
        this.state = {
            canvas: null,
            colorInfo: null
        };
    }

An alternative would be passing setSelectedItems to the zoom functions and calling it there. But since zooming is not changing the items selected I thought this would be better.

I am new to the project. Would you want a PR for this?
