### ISSUE TITLE
Not able to delete selection on touch device

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-paint#277]
You can select things, but cannot delete them on a touch device like an iPad.

/cc @carljbowman

**Comment by Jacco** [comment]
Hi,

I think the solution to this issue would be creating a button for it (like the Scratch 2.0 editor has). Since iPads do not have a keyboard. In my opinion a good place would be next to the copy and paste buttons.

I have prepared  some code but do not have the artwork for the icon on the button. Would you want me do fix this for you in this way? (I know the issue does not have the HELP WANTED label, but I am very eager to contribute to this project)

Regards, Jacco

**Comment by fsih** [comment]
@carljbowman what icon should we use?

**Comment by carljbowman** [comment]
![delete](https://user-images.githubusercontent.com/3409578/40238621-bb49ec02-5a81-11e8-875c-d8acbef02915.png)
### UX
Delete should be a state tool for the Select Tool and Direct Select Tool. Like other state tools, it should only appear active when a shape (Select Tool) or a point (Direct Select Tool) is selected.

Deleting a shape is pretty clear. But we need to make a decision on deleting a point. There are two things that could happen:
1. The point is deleted and the path of the shape becomes open.
2. The point is removed off the path of the shape, but the shape remains closed. 

### Asset
[delete.svg.zip](https://github.com/LLK/scratch-paint/files/2017144/delete.svg.zip)
