### ISSUE TITLE
README.md has first person

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-paint#293]
>If you are using Windows, I recommend using Ubuntu on Windows, which will allow you to use Linux commands on Windows. You will need administrator permissions.

Who's "I"? 😛

**Comment by fsih** [comment]
I think first person is OK here, and hopefully people can tell "I" is one of the authors of the repo. Sometimes first person is avoided in sciency writing because it's trying to convey that what's being said is fact--it doesn't change based on what the author thinks, or what the reader thinks, or who did what, it's just how the world works. But on Scratch, we have lots of tool-tips right now that read, "We're working on it! <smiley face>". It's a little indication that the ones working on Scratch are actual people somewhere, and we're here to listen to your thoughts and suggestions, and we're not a fact of nature, marching ever, inexorably, toward Launch.

For instance, it's just an opinion that using 601 to mean GUI is silly :p so it feels weird to take "I" out of that. But that's just my 2 cents.
