### ISSUE TITLE
Scratch 2.0 project background imported in the wrong place

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-paint#342]
This project loads with the backdrops offset up and to the left:
https://preview.scratch.mit.edu/#209781807

The "Title screen" backdrop looks like this in the editor:
![image](https://user-images.githubusercontent.com/13686399/37985432-95c32392-31ad-11e8-9f16-c2c1ab08e604.png)

But should look like this:
![image](https://user-images.githubusercontent.com/13686399/37985466-a90c12ce-31ad-11e8-8def-691dc8fc924e.png)

**Comment by Mr-Dave2** [comment]
This looks related to this issue [](url)https://github.com/LLK/scratch-render/issues/238 Background offset on this project.

I made this small project that has the same problem
https://preview.scratch.mit.edu/#215640722
![off center background](https://user-images.githubusercontent.com/35544966/38685883-a16e8fe6-3e38-11e8-9e62-a752d15d84a0.png)

**Comment by fsih** [comment]
@Mr-Dave2 do you have repro steps for how you reconstructed the problem? That would be super helpful

**Comment by Mr-Dave2** [comment]
To recreate
Start a new Scratch 2.0 project,
Click on Paint a new sprite,
Change paint editor to vector mode,
Select the line tool and change size to about 50%.
Draw a horizontal line.
Change color, draw a second line on top of the first.
I duplicated this sprite to show before and after,
In the new sprite (named Top Lines), group the lines,
Use the select tool with the mouse to grab the top middle change point of the newly groups lines.
I only  dragged the “square rubber band” higher.  This makes them both fatter – which is something that the Scratch 3.0 paint editor does not do.  Also, It looks like I rotated the grouped lines but that’s only because my initial lines were not perfectly horizontal.
Save the project, close Scratch 2.0, open the project in a Scratch 3.0 session.

**Comment by Mr-Dave2** [comment]
I'm sorry.. let me try this again (wrong project steps - but I had those already written out).
The steps were:
Start a new Scratch 2.0 project
Made a new sprite (paint),
Vector mode,
Black square for the background.
Made a yellow square and copied it.  Move one left, one right,
Grouped all three.
dragged the group to the left and down,
dragged the costume to the stage. 
Went to the stage and selected this new backdrop.  Noticed that it was centered.
Opened project in Scratch 3.0  and noticed that it was off-centered - just like the sprite.
