### ISSUE TITLE
Brush cursor preview moves away from mouse if you scroll

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#401]
### Expected Behavior

Cursor preview should stay stuck to mouse

### Actual Behavior

Cursor preview can be scrolled away

### Steps to Reproduce

1. Be on the brush tool (either bitmap or vector)
2. Zoom in
3. Scroll

### Operating System and Browser
Windows 10 Chrome

**Comment by Jacco** [comment]
This was a puzzle to find out. What appeared that the view is not sending any event to the tool while panning/zooming (handled by ScrollableCanvas). First I though of sending a "fake" event directly to the tool but then the dragging state was lost. Then I found a way to have the view send the event to the tool so that the dragging state is kept.

It is a bit hacky to call the private method on the view. Let me know if you want a pull request :-)

BTW gratz on the release, also the code looks much cleaner now :-)

` if (paper.tool) {
paper.tool.view._handleMouseEvent('mousemove', event, fixedPoint)
}`

**Comment by Jacco** [comment]
With this fix you can even draw using panning in stead of moving  :-)

![untitled](https://user-images.githubusercontent.com/1318341/52393548-d223a580-2aa6-11e9-95b6-97376295559b.gif)

**Comment by Jacco** [comment]
@fsih fixes this one too

**Comment by Jacco** [comment]
@paulkaplan this one can be closed now :-)
