### ISSUE TITLE
Vector lines sometimes don't draw as thick in the paint editor as they do on the stage

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-paint#618]
[In this project, 56534898, ](https://llk.github.io/scratch-gui/develop/#56534898) Most of the vector art is drawn with thin lines in the paint editor but with thick lines on the stage.  

![screen shot 2018-08-23 at 9 37 29 am](https://user-images.githubusercontent.com/1088291/44529146-592bbf80-a6b9-11e8-9053-a4b69d13bb26.png)

The stage better matches 2.0, so the paint editor should show the lines thicker. 
![screen shot 2018-08-23 at 9 36 57 am](https://user-images.githubusercontent.com/1088291/44529183-75c7f780-a6b9-11e8-959c-4de01d1c4a77.png)

An example of it behaving correctly is this project: https://beta.scratch.mit.edu/#240179841
![screen shot 2018-08-23 at 9 54 06 am](https://user-images.githubusercontent.com/1088291/44529602-82991b00-a6ba-11e8-9ffd-0b203d2dd4fd.png)
I'm not sure yet exactly why it looks wrong in the first project and not the second.

Chrome on Mac

**Comment by BryceLTaylor** [comment]
I think that the character in that costume of story was created very small and then scaled up.  In 2.0 this scales the thickness, but in 3.0 it doesn't.

I believe that it is based off of the costume "stand" in the "Player" sprite.

I reproduced it here in this project: https://beta.scratch.mit.edu/#240186020
![screen shot 2018-08-23 at 10 43 27 am](https://user-images.githubusercontent.com/1088291/44532606-795f7c80-a6c1-11e8-93e7-e84923eb285c.png)

**Comment by fsih** [comment]
Here's what render is getting
```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="89.0321044921875" height="130.59219360351562" viewBox="9.63156509399414 9.54062557220459 89.0321044921875 130.59219360351562">
   <!-- Exported by Scratch - http://scratch.mit.edu/ -->
   <path id="ID0.19577441923320293" fill="none" stroke="#000000" stroke-width="2" d="M 235.700 173.250 L 244.600 173.250 L 244.600 186.400 L 235.700 186.400 L 235.700 173.250 Z " transform="matrix(9.778878211975098, 0, 0, 9.778878211975098, -2294.25, -1683.65)" />
</svg>
```
Here's what we get after import & export from paper
```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="89.03202" height="130.59225" viewBox="-1,-1,89.03202,130.59225">
   <g transform="translate(-197.63159,-117.54065)">
      <g data-paper-data="{&quot;isPaintingLayer&quot;:true}" fill="none" fill-rule="nonzero" stroke="#000000" stroke-width="2" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal">
         <path d="M197.63159,117.54065h87.03202v128.59225h-87.03202z" id="ID0.19577441923320293" />
      </g>
   </g>
</svg>
```
So there's no scale on the stroke width anymore...

**Comment by fsih** [comment]
I wrote up https://github.com/paperjs/paper.js/issues/1514 which sums up the issue in Paper and why it's hard to solve. Essentially we lose the information about how the stroke was transformed (and thereby have no way to correct it outside paper) unless we set global applyMatrix = false. However this would break editing everywhere else since we currently make assumptions about the item coordinate systems matching the global coordinate system (which is what applyMatrix does).

However, I've found that SVG import is only part of the issue. The SVG Scratch 2 exports does not look like what it displays. x_x
Compare https://scratch.mit.edu/projects/248347877/#editor and https://beta.scratch.mit.edu/#248347877
![image](https://user-images.githubusercontent.com/2855464/46020353-3459ac00-c0ac-11e8-9a21-bce5c81e3bfa.png)
![image](https://user-images.githubusercontent.com/2855464/46020380-42a7c800-c0ac-11e8-93f0-8639fa9e160a.png)
3 different images here u_u
The black thin line is drawn where the bounding box of the rectangle in Scratch 2 appears. We will have to figure out how it's getting this bounding box for this shape... going by the way it matches in the new renderer, I think it's the bounds of the svg when it's actually transformed by the transformation matrix, but Scratch 2 is drawing the same shape with a stroke width that is somehow averaged out.

**Comment by fsih** [comment]
I think the fix belongs in SVGRenderer, that way we can fix scratch-render too and circumvent the issue in Paper.
/cc @cwillisf if you have any thoughts, since I will probably be asking you to review (if you have any idea where in scratch-flash the relevant code is that would be cool)

**Comment by fsih** [comment]
https://github.com/LLK/scratch-flash/blob/74ae0cbc0427d6acc0508e41a73a324f84ebc8c4/src/svgeditor/tools/RectangleTool.as#L54

Oddly the flash code doesn't seem to have tried to do anything special to even out the stroke widths

**Comment by fsih** [comment]
@cwillisf helped me track down where shape rendering happens in the Flash code, at https://github.com/LLK/scratch-flash/blob/646523e6846ad0dd993213a38b46fe2ea511d026/src/svgutils/SVGDisplayRender.as#L88
The transformation is not dealt with in our Flash code, but is passed to the created Flash Shape to handle. Unfortunately, Flash is a big not-open-source black box, so the trail ran cold here.

After far too much drawing sample rectangles and counting the difference in the number of pixels in the stroke to collect data, I've finally figured out that **the percent change in the stroke width drawn by Flash is equal to the quadratic mean of the percent change in the width and the percent change in the height.** (Incidentally, on the way I discovered that Illustrator uses the geometric mean, which I think makes a lot more sense. The quadratic mean is so0o last century.)

The fix should probably happen in scratch-svg-renderer so that scratch-render also gets fixed. The SVG tree would need to be traversed to push all group transforms down to the leaf level. (See https://github.com/LLK/scratch-flash/blob/646523e6846ad0dd993213a38b46fe2ea511d026/src/svgutils/SVGImporter.as#L347 Note that the comment here about transforms being applied to paths is false) Then the transform needs to be manually resolved on path elements (see https://github.com/LLK/scratch-flash/blob/646523e6846ad0dd993213a38b46fe2ea511d026/src/svgutils/SVGPath.as#L117) with the stroke-width attribute adjusted as described above.
