### ISSUE TITLE
Hole got filled in when filling a different hole in a compound path

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#639]
Filling the owl-b costume with two different gradients fills some other parts of the owl with black on the stage (eye and breast). (Undo/Redo also changes the parts that are black) @chrisgarrity 
![image54](https://user-images.githubusercontent.com/1088291/44663445-93110480-a9de-11e8-80c8-4f9631a8dfea.png)
![image58](https://user-images.githubusercontent.com/1088291/44663405-770d6300-a9de-11e8-9876-c47e42945248.png)

**Comment by BryceLTaylor** [comment]
This is two bugs.  One of them is on all browsers which causes a strange, but largely unnoticeable behavior.  The other is with firefox specifically, where it responds poorly to the behavior of the first one.

First, the general one.  The outlines of the Owl sprite are single closed paths with a black stroke and a transparent fill.  You can click through the transparent fill and it more or less behaves as expected.

The problem is, that if you use the fill tool on a closed single path, it doesn't matter if it's a gradient or not, it will turn all of the other closed single paths and add a fill to them that is a gradient from black to transparent.

On most browsers, this black to transparent gradient appears only transparent on both the paint editor and the stage.

The Firefox bug is that this gradient appears black on the stage but transparent on the paint editor.

In all browsers, you can now click in the middle of closed single path with the select tool and you will select the whole shape as if it were filled.  After this you can never use the paint bucket to change the fill to transparent, nor can you set the fill while the shape is selected.

You can easily reproduce this by drawing a few circles with the circle tool that have a transparent fill, then use the paint bucket to fill one of the circles.  For some reason that I haven't figured out yet you don't get this result sometimes, but trying again usually will get the result.

**Comment by fsih** [comment]
oh no

**Comment by BryceLTaylor** [comment]
This is now happening on Chrome as well.

@me-win reported an issue that came in from a user from Twitter:
Hey scratch, my Ss found a bug, we think, when editing a Sprite, they tried to change eye color to red, but when it renders, the whole head turns black, you can see in the image

![screen shot 2019-02-15 at 9 57 00 am](https://user-images.githubusercontent.com/1088291/52864502-4cd46c80-3108-11e9-8ec0-8137438e8e5d.png)

It appears they were on a chromebook.

@me-win reproduced it:
![image](https://user-images.githubusercontent.com/1088291/52864181-9a040e80-3107-11e9-9239-0b4a552b4d73.png)

I can also reproduce it on Chrome on Mac with the owl (screenshots look the same as those posted above.)

**Comment by paulkaplan** [comment]
@BryceLTaylor could you add step-by-step instructions for reproducing the cat issue? I can't repro.

**Comment by paulkaplan** [comment]
Woops nevermind, I was able to do it. I was getting stuck trying to use the selection+fill color, didn't realize I should have been using paint bucket.

1. Add Cat Flying-a
2. Use paint bucket tool
3. Click the white part of the left eye
4. See the head turn black on the stage but not in the costume editor

**Comment by paulkaplan** [comment]
I've been using as a test case an SVG with two squares (`path`s in the svg). Both have transparent fill, black outline.
![image](https://user-images.githubusercontent.com/654102/53898068-667d1b80-4005-11e9-8aff-53dfa25ce81d.png)

If I fill the first square, it works and looks correct. Inspecting the SVG, there is no strange gradienting.
![image](https://user-images.githubusercontent.com/654102/53898137-80b6f980-4005-11e9-9e20-9fb9b35075b9.png)

But if I fill the second square, I get the bug
![image](https://user-images.githubusercontent.com/654102/53898337-dc818280-4005-11e9-8597-461a4a92938b.png)

And looking in the SVG, I see what @BryceLTaylor was describing. The first square (the one I didn't use the fill bucket on) gets a fill with
```
        <linearGradient x1="0" y1="0" x2="0" y2="0" gradientUnits="userSpaceOnUse" id="color-1">
            <stop offset="0" stop-color="#000000" stop-opacity="0" />
            <stop offset="1" stop-color="#000000" />
        </linearGradient>
```
It isn't surprising that different renderers disagree about what to show, since this gradient basically makes no sense. 

If I use 3 squares and fill the middle one, I get the bad fill on the first square but not the last square, which suggests an ordering issue where it could be trying to merge layers behind the picked one or something.
![image](https://user-images.githubusercontent.com/654102/53898598-67627d00-4006-11e9-8588-7ef8ec1672cd.png)

The fact that the gradient does not depend on the chosen fill color makes me hopeful about tracking this down though.
