### ISSUE TITLE
Paint editor: Vertical flip rotates

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-paint#810]
Just in case it wasn't implemented like this on purpose:

### Expected Behavior

When clicking the "Flip Vertically" button in the paint editor, the costume is mirrored on a horizontal axis.

### Actual Behavior

When clicking the "Flip Vertically" button in the paint editor, the costume is rotated 180°.

### Steps to Reproduce

See above

### Operating System and Browser

Windows 10 Home, Firefox 64.0

---
Moved from LLK/scratch-blocks#1842
/cc @gunchleoc

**Comment by thisandagain** [comment]
(See valuable repro information on the prior issue filed in the `scratch-blocks` repo)

**Comment by joker314** [comment]
**Still unable to reproduce.**

Here were the steps to reproduce I originally used (which showed the cat flipping as intended, not rotating):

> 1. Open a new project
> 2. Navigate to the Scratch Cat's costumes and select the first one
> 3. Add a purple circle in the top-right of the cat
> 4. Select the 'Selection' tool again
> 5. Hit the 'Flip Vertically' button
>
> Observe that the purple circle you drew appears in the bottom-**right**, not the bottom-**left**. This means it _is_ being mirrored rather than rotated. :slightly_smiling_face:

However, @gunchleoc then noted that:
> I am skipping step 3 and 4

They also attach a video.

I am able to reproduce the behaviour in the video, but believe this to be the **intended** behaviour. Here are some steps to show that the correct behaviour is happening (even without adding a purple circle).

1. Open a new project
2. Navigate to the Scratch Cat's costumes and select the first one
3. Observe that the cat's tail is in the bottom-**left**
4. Hit 'Flip Vertically'

Observe that the tail is in the top-**left**. Had there been a rotation rather than a reflection it would be in the top-right. Do you agree @gunchleoc?

**Comment by fsih** [comment]
In the video, it appears to me that the scratch cat is mirrored over its center horizontal axis as intended

**Comment by gunchleoc** [comment]
You are right, I was seeing things - all correct!

Please close this issue.
