### ISSUE TITLE
Making costume empty in paint editor doesn't update stage right away

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#901]
### Expected Behavior

Any changes in the paint editor should be immediately reflected on the stage.

### Actual Behavior

If you make a costume empty through the paint editor (i.e. by deleting or erasing the last remaining shapes), the stage won't immediately be updated. (Once some other change is made, and the stage does update, it'll reflect the shapes having been deleted.)

### Steps to Reproduce

Delete the last shape in a costume editor, so that the costume is empty. Note that the stage doesn't update until you make some other change.

### Operating System and Browser

Firefox 66.0b8.

---
Moved from LLK/scratch-gui#4569
/cc @towerofnix

**Comment by kchadha** [comment]
It looks like this is a bug in scratch-render caused by calling `context.getImageData` with values of 0 for the width and height of the rectangle. These are not valid values for that function or for `context.createImageData`. We need to figure out how to handle blank costumes between paint and render.
