### ISSUE TITLE
Color picker crashes on Safari

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#966]
### Expected Behavior
Eyedropper should pick colors

### Actual Behavior
Eyedropper crashes
Edit: Seems to be browser-width related. This reproes for me at browser width 1257.

1. Go to costume tab (vector or bitmap, doesn't matter)
2. Stay on select tool
3. Open color picker (fill or outline, doesn't matter)
4. Click on eyedropper icon

### Steps to Reproduce
Click on eyedropper at the bottom of the color picker dropdown in the paint editor

### Operating System and Browser
Mac 10.14.6 Safari  13.0.5

**Comment by fsih** [comment]
<img width="755" alt="Screen Shot 2020-01-31 at 10 43 07" src="https://user-images.githubusercontent.com/2855464/73552614-8a63ff80-4416-11ea-98e4-35b18a20f4ba.png">

**Comment by paulkaplan** [comment]
@fsih I have a more consistent repro.

1. Bitmap or Vector, doesn't matter what tool selected, just open a color picker and click the eyedropper
2. With the eyedropper active, move your mouse all the way to the left. Slowly move your mouse to the right (any Y is fine) and you will see the crash. The crash occurs when your mouse is ~X=20px. That is about two grid squares from the left edge. That crashes it every time on Safari, but not on Chrome

I've looked into the cause, and here is what I am seeing.
- Getting the loupe image data comes from `eye-dropper.js` using `getImageData`. 
- That image data is drawn to a canvas in `loupe.jsx`, by creating a temp canvas, creating an imageData object and using `imgData.data.set(<data from eyedropper>)`. I'll call the loupe's imgData the `destination` and the eye-dropper imgData the `source` for clarity.
- Using `destination.set(source)` throws errors if `source` is larger than `destination`. 
- The x value passed to eye-dropper getImageData is `zoom * (artX - loupeRadius)`, so it will be ~0 when your mouse is around the loupeRadius, 20px. 
- Logging that value, it is actually `-9.947598300641403e-14`
- Calling `getImageData(x=<negative almost zero>, w=120)` returns an ImageData with width 120 in Chrome, __but width 121 in Safari__. You can repro this by inspecting the results of this in the inspector:```console.log(document.createElement('canvas').getContext('2d').getImageData(-9.947598300641403e-14, 0, 120, 120));```
- Using that w=121 imageData causes an uncaught exception because the destination is smaller (w=120).

Changing the `eye-dropper.js` function to do the subtraction before the scaling removes the floating point "almost zero" situation, and prevents this bug from happening. That is
```
ZOOM_SCALE * (artX - LOUPE_RADIUS)
```
instead of 
```
(artX * ZOOM_SCALE) - (LOUPE_RADIUS * ZOOM_SCALE)
```

It does seem like a Safari bug that you can get 121px width imageData when you ask for 120px imageData, but we also might want to be more defensi e when using data.put...

**Comment by fsih** [comment]
Thanks Paul!!
